"""initial schema

Revision ID: 9898aa51d5c7
Revises: eff765930201
Create Date: 2026-07-23 13:26:52.795609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9898aa51d5c7'
down_revision: Union[str, Sequence[str], None] = 'eff765930201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_problem_templates',
    sa.Column('problem_id', sa.String(length=4), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('run_test_cases', sa.JSON(), nullable=False),
    sa.Column('time_limit', sa.Float(), nullable=False),
    sa.Column('submit_test_cases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.add_column('problem_templates', sa.Column('main_code', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'problem_templates', 'common_problem_templates', ['problem_id'], ['problem_id'], ondelete='CASCADE')
    op.drop_column('problem_templates', 'submit_test_cases')
    op.drop_column('problem_templates', 'time_limit')
    op.drop_column('problem_templates', 'run_test_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_templates', sa.Column('run_test_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('problem_templates', sa.Column('time_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('problem_templates', sa.Column('submit_test_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'problem_templates', type_='foreignkey')
    op.drop_column('problem_templates', 'main_code')
    op.drop_table('common_problem_templates')
    # ### end Alembic commands ###
