"""initial migration

Revision ID: eff765930201
Revises: 
Create Date: 2026-07-22 23:45:13.618844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff765930201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_templates',
    sa.Column('problem_id', sa.String(length=4), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('user_code', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Float(), nullable=False),
    sa.Column('run_test_cases', sa.JSON(), nullable=False),
    sa.Column('submit_test_cases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id', 'language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_templates')
    # ### end Alembic commands ###
